server:
  port: 8082
  servlet:
    context-path: /api/it2

spring:
  profiles:
    active: #spring.profiles.active#
    default: dev
  datasource:
    # 连接池
    hikari:
      # 连接池名
      pool-name: LmccHikariCP
      #最小空闲连接数
      minimum-idle: 10
      # 空闲连接存活最大时间. 默认 600000, 10 分钟
      idle-timeout: 180000
      # 连接池最大连接数, 默认是 10
      maximum-pool-size: 60
      # 此属性控制从池返回的连接的默认自动提交行为, 默认值: true
      auto-commit: true
      # 此属性控制池中连接的最长生命周期, 值 0 表示无限生命周期, 默认 1800000 即 30 分钟
      max-lifetime: 1800000
      # 数据库连接超时时间, 默认 60 秒, 即 60000
      connection-timeout: 60000
      connection-test-query: SELECT 1

db:
  page-size: 15
