spring:
  datasource:
    url: jdbc:mysql://$(?):3306/lmcc?autoReconnect=true&failOverReadOnly=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    username:
    password:

logging:
  file:
    name: /home/xiayi/SE3/backend/logs/log
  level:
    org:
      springframework:
        boot:
          autoconfigure:
            logging: info