pipeline {
    agent any

    stages {
        stage('begin') {
            steps {
                echo "== Start CICD =="
            }
        }

        stage('pull') {
            steps {
                git credentialsId: 'e81c1ce7-3228-413f-b702-02d111f54a17', url: 'git@git.nju.edu.cn:191250045/lmcc-backend-mirror.git'
                sh 'pwd'
                sh 'ls -al'
            }
        }

        stage('all') {
            steps {
                gitlabCommitStatus( name: 'all', connection:gitLabConnection('lmcc'), builds: [
                    [projectId: '191250045/lmcc-backend-mirror', revisionHash: 'master']
                ]){
                    sh "make -f scripts/Makefile"
                }
                jacoco inclusionPattern: '**/target/classes/**/clockcourier/controller/*.class; **/target/classes/**/clockcourier/dao/impl/*.class; **/target/classes/**/clockcourier/service/impl/*.class',
                       execPattern: '**/target/**.exec', sourceInclusionPattern: '**/*.java'
            }
        }

        stage('end') {
            steps {
                echo '== The End =='
            }
        }
    }
}