pipeline {
    agent any

    stages {
        stage('begin') {
            steps {
                echo "== Start CICD =="
            }
        }

        stage('pull') {
            steps {
                git credentialsId: 'e81c1ce7-3228-413f-b702-02d111f54a17', url: 'git@git.nju.edu.cn:191250045/lmcc-backend-mirror.git'
                sh 'pwd'
                sh 'ls -al'
            }
        }

        stage('all') {
            steps {
                gitlabCommitStatus( name: 'all', connection:gitLabConnection('lmcc'), builds: [
                    [projectId: '191250045/lmcc-backend-mirror', revisionHash: 'master']
                ]){
                    sh "make -f scripts/Makefile"
                }
                jacoco execPattern: '**/target/**.exec',
                       classPattern: '**/target/classes/com/edu/nju/clockcourier/controller, **/target/classes/com/edu/nju/clockcourier/service, **/target/classes/com/edu/nju/clockcourier/dao/impl',
                       sourcePattern: '**/src/main/java/com/edu/nju/clockcourier'
            }
        }

        stage('end') {
            steps {
                echo '== The End =='
            }
        }
    }
}